// Auto-generated by @laravel/wayfinder (stub for sandbox environment)
// In production, this is generated by: php artisan wayfinder:generate

type WayfinderResult = {
    url: string;
    toString(): string;
    form(): { action: string; method: string };
};

function route(url: string, method: string = 'GET'): WayfinderResult {
    return { url, toString: () => url, form: () => ({ action: url, method }) };
}

export function home(): WayfinderResult {
    return route('/');
}

export function login(): WayfinderResult {
    return route('/login', 'GET');
}

export function register(): WayfinderResult {
    return route('/register', 'GET');
}

export function logout(): WayfinderResult {
    return route('/logout', 'POST');
}

export function dashboard(teamSlug: string): WayfinderResult {
    return route(`/${teamSlug}/dashboard`, 'GET');
}
